### ISSUE TITLE
added fastq model and database is not reflecting changes

### ISSUE THREAD

**Issue by katherinemwong** [YeoLab/metadata-db#7]
I defined a Fast model (which is now renamed to Fastq), redid migrations, and i'm getting the error: `django.db.utils.OperationalError: no such table: blog_fast`. This used to occur after when I tried to add a fastq when testing it on the server, but after updating VSCode, I'm getting this error when I run `python manage.py migrate blog` after makemigration. Not too sure what the issue is here, but I think it might be because I'm not creating objects correctly before retrieving them? 

Solutions I tried: 

1. Deleting all past migration files and redoing migrations. I thought this would help because I thought maybe I had made to many changes to the models that it may have messed something up so I wanted to start with a clean slate. 

2. Going into the shell and /admin and trying to create objects there. I get the same error message when I perform `Fastq.objects.get()` or when I do `Fastq.objects.create(title=txt, complete=False)` where txt = string input for fastq in the form. 

Here's the tutorial I followed: https://www.techwithtim.net/tutorials/django/custom-forms/.
I'm not exactly knowledgable in how the backend works so I'm having trouble debugging this. 

@byee4

**Comment by byee4** [comment]
I see. Which branch is your latest commit in?

**Comment by byee4** [comment]
I just quickly tried loading the origin/yaml_feature_1 branch, and was able to reproduce the error. However removing the migrations files (but keeping __init__.py) seemed to fix things for me

```
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: blog_fast
(metadata-db-env) (base) brians-mbp:metadata-db brianyee$ python manage.py makemigrations blog
Migrations for 'blog':
  blog/migrations/0001_initial.py
    - Create model CLIP
    - Create model Fastq
    - Create model Post
(metadata-db-env) (base) brians-mbp:metadata-db brianyee$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, blog, contenttypes, sessions
Running migrations:
  No migrations to apply.
(metadata-db-env) (base) brians-mbp:metadata-db brianyee$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 04, 2022 - 11:13:39
Django version 3.2.14, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[04/Sep/2022 11:13:44] "GET / HTTP/1.1" 200 5137
Not Found: /favicon.ico
[04/Sep/2022 11:13:44] "GET /favicon.ico HTTP/1.1" 404 2995

```

**Comment by katherinemwong** [comment]
Sorry for the late reply, it is the yaml_feature_1 branch. Do you get this same error when you try to add a fastq to the form?

**Comment by byee4** [comment]
Oh, I see what you mean. I ended up moving the existing database elsewhere so Django had to make a new one, that seemed to have triggered the table creation properly. Not sure why the existing db wasn't updating, maybe something to look into?
